import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { decrypt, encrypt } from "@/lib/crypto";
import { db } from "@/lib/db";
import { requireSameOrigin } from "@/lib/security";

type DriveConfig = { accessToken: string; refreshToken?: string };
type DriveFile = { id: string; name: string; mimeType: string; webViewLink?: string };
async function accessToken(config: DriveConfig) { const first = await fetch("https://www.googleapis.com/drive/v3/files?pageSize=100&fields=files(id,name,mimeType,webViewLink)", { headers: { Authorization: `Bearer ${config.accessToken}` }, cache: "no-store" }); if (first.ok) return { response: first, config }; if (first.status !== 401 || !config.refreshToken) return { response: first, config }; const refresh = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID || "", client_secret: process.env.GOOGLE_CLIENT_SECRET || "", refresh_token: config.refreshToken, grant_type: "refresh_token" }) }); if (!refresh.ok) return { response: first, config }; const tokens = await refresh.json() as { access_token: string }; const next = { ...config, accessToken: tokens.access_token }; return { response: await fetch("https://www.googleapis.com/drive/v3/files?pageSize=100&fields=files(id,name,mimeType,webViewLink)", { headers: { Authorization: `Bearer ${next.accessToken}` }, cache: "no-store" }), config: next }; }
export async function POST(request: NextRequest) { const forbidden = requireSameOrigin(request); if (forbidden) return forbidden; const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const integration = await db.integration.findUnique({ where: { userId_provider: { userId: user.id, provider: "google-drive" } } }); if (!integration) return NextResponse.json({ error: "Connect Google Drive first." }, { status: 400 }); try { const result = await accessToken(JSON.parse(decrypt(integration.configEncrypted)) as DriveConfig); if (!result.response.ok) throw new Error("Google Drive sync failed. Reconnect your account."); const data = await result.response.json() as { files?: DriveFile[] }; const workspace = await db.workspace.findFirst({ where: { ownerId: user.id, name: "Personal" } }) ?? await db.workspace.findFirst({ where: { ownerId: user.id } }); if (!workspace) throw new Error("No workspace is available."); let added = 0; for (const file of data.files || []) { const url = file.webViewLink || `https://drive.google.com/open?id=${file.id}`; if (!await db.brainItem.findFirst({ where: { workspaceId: workspace.id, url } })) { await db.brainItem.create({ data: { title: file.name, type: "link", url, description: file.mimeType, x: 12 + ((added * 17) % 76), y: 12 + ((added * 23) % 76), color: "green", tags: ["Google Drive"], workspaceId: workspace.id } }); added += 1; } } await db.integration.update({ where: { id: integration.id }, data: { configEncrypted: encrypt(JSON.stringify(result.config)), lastSyncedAt: new Date(), syncStatus: "ready" } }); await db.auditLog.create({ data: { userId: user.id, action: "google_drive.synced", detail: `${added} files added` } }); return NextResponse.json({ added, total: data.files?.length || 0 }); } catch (error) { await db.integration.update({ where: { id: integration.id }, data: { syncStatus: "error" } }); return NextResponse.json({ error: error instanceof Error ? error.message : "Google Drive sync failed." }, { status: 500 }); } }
