import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { requireSameOrigin } from "@/lib/security";

const itemSchema = z.object({ title: z.string().trim().min(1).max(120), type: z.enum(["file", "link", "note", "task", "folder"]), workspaceId: z.string().optional(), description: z.string().max(5000).optional(), url: z.string().url().optional(), x: z.number().min(0).max(100).default(50), y: z.number().min(0).max(100).default(50), color: z.string().max(20).default("cyan"), tags: z.array(z.string().max(30)).max(12).default([]), dueAt: z.string().datetime().optional() });
export async function GET() { const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const workspaces = await db.workspace.findMany({ where: { ownerId: user.id }, include: { items: { where: { deletedAt: null, isArchived: false }, orderBy: { updatedAt: "desc" } } }, orderBy: { createdAt: "asc" } }); return NextResponse.json({ workspaces }); }
export async function POST(request: NextRequest) { const forbidden = requireSameOrigin(request); if (forbidden) return forbidden; const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = itemSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Check the item details and try again." }, { status: 400 }); const workspace = parsed.data.workspaceId ? await db.workspace.findFirst({ where: { id: parsed.data.workspaceId, ownerId: user.id } }) : await db.workspace.findFirst({ where: { ownerId: user.id }, orderBy: { createdAt: "asc" } }); if (!workspace) return NextResponse.json({ error: "Workspace not found." }, { status: 404 }); const item = await db.brainItem.create({ data: { ...parsed.data, workspaceId: workspace.id, dueAt: parsed.data.dueAt ? new Date(parsed.data.dueAt) : undefined } }); await db.auditLog.create({ data: { userId: user.id, action: "item.created", detail: item.id } }); return NextResponse.json({ item }, { status: 201 }); }
