import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { requireSameOrigin } from "@/lib/security";

const updateSchema = z.object({ title: z.string().trim().min(1).max(120).optional(), description: z.string().max(40_000).nullable().optional(), workspaceId: z.string().optional(), x: z.number().min(0).max(100).optional(), y: z.number().min(0).max(100).optional(), tags: z.array(z.string().max(30)).max(12).optional(), isCompleted: z.boolean().optional(), isArchived: z.boolean().optional(), restore: z.boolean().optional() });
async function ownedItem(id: string, userId: string) { return db.brainItem.findFirst({ where: { id, workspace: { ownerId: userId } } }); }
export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const item = await ownedItem((await params).id, user.id); if (!item || item.deletedAt) return NextResponse.json({ error: "Item not found." }, { status: 404 }); return NextResponse.json({ item }); }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const forbidden = requireSameOrigin(request); if (forbidden) return forbidden; const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const item = await ownedItem((await params).id, user.id); if (!item) return NextResponse.json({ error: "Item not found." }, { status: 404 }); const parsed = updateSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Invalid item update." }, { status: 400 }); if (parsed.data.workspaceId && !await db.workspace.findFirst({ where: { id: parsed.data.workspaceId, ownerId: user.id } })) return NextResponse.json({ error: "Workspace not found." }, { status: 404 }); const { restore, ...data } = parsed.data; const updated = await db.brainItem.update({ where: { id: item.id }, data: { ...data, deletedAt: restore ? null : undefined } }); await db.auditLog.create({ data: { userId: user.id, action: "item.updated", detail: item.id } }); return NextResponse.json({ item: updated }); }
export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const forbidden = requireSameOrigin(request); if (forbidden) return forbidden; const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const item = await ownedItem((await params).id, user.id); if (!item) return NextResponse.json({ error: "Item not found." }, { status: 404 }); await db.brainItem.update({ where: { id: item.id }, data: { deletedAt: new Date() } }); await db.auditLog.create({ data: { userId: user.id, action: "item.trashed", detail: item.id } }); return NextResponse.json({ ok: true }); }
