"use client";

import { ExternalLink, FileText, Pencil, Save, Trash2, X } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";

type Item = { id: string; title: string; type: string; description: string | null; url: string | null; filePath: string | null; mimeType: string | null; tags: string[]; workspaceId: string };
type Workspace = { id: string; name: string };

export default function ItemPage() {
  const params = useParams<{ id: string }>(); const router = useRouter();
  const [item, setItem] = useState<Item | null>(null); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [error, setError] = useState(""); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [workspaceId, setWorkspaceId] = useState(""); const [tags, setTags] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void Promise.all([fetch(`/api/items/${params.id}`).then((response) => response.json().then((data) => ({ response, data }))), fetch("/api/workspaces").then((response) => response.json())]).then(([result, spaces]) => { if (!result.response.ok) { setError(result.data.error); return; } setItem(result.data.item); setTitle(result.data.item.title); setDescription(result.data.item.description || ""); setWorkspaceId(result.data.item.workspaceId); setTags(result.data.item.tags.join(", ")); setWorkspaces(spaces.workspaces || []); }); }, [params.id]);
  async function save(event: FormEvent) { event.preventDefault(); if (!item) return; setBusy(true); const response = await fetch(`/api/items/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, description: description || null, workspaceId, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean).slice(0, 12) }) }); const data = await response.json(); setBusy(false); if (!response.ok) { setError(data.error || "Could not save changes."); return; } setItem(data.item); setTags(data.item.tags.join(", ")); setEditing(false); }
  async function trash() { if (!item) return; setBusy(true); const response = await fetch(`/api/items/${item.id}`, { method: "DELETE" }); if (response.ok) router.replace("/trash"); else { const data = await response.json(); setError(data.error || "Could not move the item to trash."); setBusy(false); } }
  if (error && !item) return <main className="share-page"><section className="share-card"><h1>{error}</h1><a className="primary-button auth-submit" href="/">Return home</a></section></main>;
  if (!item) return <main className="share-page"><section className="share-card"><h1>Opening item...</h1></section></main>;
  const preview = item.filePath && (item.mimeType === "application/pdf" || item.mimeType?.startsWith("image/"));
  return <main className="item-page"><header className="calendar-head"><a href="/">NRC Second Brain</a><span>Private item</span><a className="tool-button" href="/">Back to graph</a></header><section className="item-content"><div className="item-heading"><div><p className="eyebrow">{item.type.toUpperCase()}</p><h1>{item.title}</h1></div><div className="item-actions"><button className="tool-button" onClick={() => setEditing(!editing)}><Pencil size={16} />{editing ? "Cancel" : "Edit"}</button><button className="danger-button" disabled={busy} onClick={() => void trash()}><Trash2 size={16} />Move to trash</button></div></div>{editing ? <form className="settings-panel item-edit-form" onSubmit={save}><label className="field">Name<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} required /></label><label className="field">Workspace<select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}>{workspaces.map((workspace) => <option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select></label><label className="field">Tags<input value={tags} onChange={(event) => setTags(event.target.value)} maxLength={360} placeholder="school, biology, exam" /></label><label className="field">Details<textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={5000} /></label><div><button className="primary-button" disabled={busy}><Save size={16} />{busy ? "Saving..." : "Save changes"}</button><button type="button" className="tool-button" onClick={() => { setTitle(item.title); setDescription(item.description || ""); setWorkspaceId(item.workspaceId); setTags(item.tags.join(", ")); setEditing(false); }}><X size={16} />Discard</button></div></form> : <><p className="settings-intro item-description">{item.description || "Saved privately on your server."}</p><div className="tag-row">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></>}{error && <p className="form-error">{error}</p>}{item.url && <a className="primary-button item-action" href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={16} />Open linked resource</a>}{item.filePath && <a className="tool-button item-action" href={`/api/files/${item.id}`} target="_blank" rel="noreferrer"><FileText size={16} />Open/download file</a>}{preview && <iframe className="file-preview" src={`/api/files/${item.id}`} title={item.title} />}{!preview && item.filePath && <div className="preview-placeholder"><FileText size={26} /><p>Use Open/download file to view this format.</p></div>}</section></main>;
}
