CREATE TABLE "VaultNote" ("id" TEXT PRIMARY KEY, "title" TEXT NOT NULL, "encrypted" TEXT NOT NULL, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "VaultNote_userId_idx" ON "VaultNote"("userId");
