import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getSession } from "@/lib/auth";
import { encrypt } from "@/lib/crypto";
import { db } from "@/lib/db";
import { requireSameOrigin } from "@/lib/security";

const tokenSchema = z.object({ token: z.string().trim().min(20).max(500) });
export async function GET() { const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const integration = await db.integration.findUnique({ where: { userId_provider: { userId: user.id, provider: "github" } }, select: { accountLabel: true, syncStatus: true, lastSyncedAt: true } }); return NextResponse.json({ integration }); }
export async function POST(request: NextRequest) { const forbidden = requireSameOrigin(request); if (forbidden) return forbidden; const user = await getSession(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = tokenSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Enter a valid GitHub personal access token." }, { status: 400 }); try { const profile = await fetch("https://api.github.com/user", { headers: { Authorization: `Bearer ${parsed.data.token}`, Accept: "application/vnd.github+json", "User-Agent": "NRC-Second-Brain" }, cache: "no-store" }); if (!profile.ok) return NextResponse.json({ error: "GitHub did not accept that token." }, { status: 401 }); const account = await profile.json() as { login: string }; await db.integration.upsert({ where: { userId_provider: { userId: user.id, provider: "github" } }, create: { userId: user.id, provider: "github", accountLabel: account.login, configEncrypted: encrypt(parsed.data.token) }, update: { accountLabel: account.login, configEncrypted: encrypt(parsed.data.token), syncStatus: "ready" } }); await db.auditLog.create({ data: { userId: user.id, action: "github.connected", detail: account.login } }); return NextResponse.json({ accountLabel: account.login }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not save the GitHub connection." }, { status: 500 }); } }
