"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Bell, ChevronDown, Code2, FileText, Folder, Grid2X2, Link2, MoreHorizontal, Plus, Search, Settings, Sparkles, Upload, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type BrainNode = { id: string; title: string; kind: "folder" | "file" | "link" | "task"; x: number; y: number; color: string; size: "small" | "medium" | "large"; detail: string; tags: string[]; };

const initialNodes: BrainNode[] = [
  { id: "math", title: "College Algebra", kind: "folder", x: 23, y: 36, color: "cyan", size: "large", detail: "Your course hub for notes, assignments, exams, and useful links.", tags: ["Dual enrollment", "Fall 2026"] },
  { id: "english", title: "English 101", kind: "folder", x: 62, y: 25, color: "blue", size: "large", detail: "Writing projects, readings, and professor resources.", tags: ["Dual enrollment", "Writing"] },
  { id: "personal", title: "Personal", kind: "folder", x: 72, y: 69, color: "violet", size: "large", detail: "Important documents, projects, and personal files.", tags: ["Private"] },
  { id: "syllabus", title: "Course syllabus", kind: "file", x: 12, y: 65, color: "cyan", size: "medium", detail: "PDF. Added today. Connected to College Algebra.", tags: ["PDF", "Important"] },
  { id: "problem-set", title: "Problem set 03", kind: "task", x: 39, y: 74, color: "amber", size: "medium", detail: "Due Friday at 11:59 PM. Open it, attach work, or mark it done.", tags: ["Assignment", "Due soon"] },
  { id: "reading", title: "Reading notes", kind: "file", x: 48, y: 48, color: "blue", size: "medium", detail: "A living note for the current English 101 reading.", tags: ["Notes", "English 101"] },
  { id: "drive", title: "Google Drive", kind: "link", x: 82, y: 39, color: "green", size: "medium", detail: "A secure shortcut to your connected Google Drive folder.", tags: ["Link", "Cloud"] },
  { id: "portfolio", title: "Portfolio ideas", kind: "file", x: 58, y: 84, color: "violet", size: "small", detail: "A note with project ideas worth revisiting.", tags: ["Personal", "Project"] },
  { id: "github", title: "GitHub", kind: "link", x: 88, y: 75, color: "slate", size: "small", detail: "Later this can show your repositories, issues, and pull requests.", tags: ["Link", "Development"] },
];
const links = [["math", "syllabus"], ["math", "problem-set"], ["math", "reading"], ["english", "reading"], ["english", "drive"], ["personal", "portfolio"], ["personal", "github"], ["drive", "github"], ["math", "english"], ["math", "personal"]];
const iconFor = (kind: BrainNode["kind"]) => kind === "folder" ? Folder : kind === "link" ? Link2 : FileText;

export default function Home() {
  const router = useRouter();
  const [nodes, setNodes] = useState(initialNodes); const [selectedId, setSelectedId] = useState("math"); const [query, setQuery] = useState(""); const [addOpen, setAddOpen] = useState(false); const [addType, setAddType] = useState<"file" | "link">("file"); const [title, setTitle] = useState(""); const [pickedFile, setPickedFile] = useState<File | null>(null); const [addError, setAddError] = useState(""); const [saving, setSaving] = useState(false);
  const selected = nodes.find((node) => node.id === selectedId) ?? nodes[0];
  const visibleNodes = useMemo(() => nodes.filter((node) => node.title.toLowerCase().includes(query.toLowerCase())), [nodes, query]);
  useEffect(() => { fetch("/api/session").then((response) => response.json()).then((data) => { if (!data.user) router.replace(data.setupComplete ? "/login" : "/setup"); }).catch(() => router.replace("/setup")); }, [router]);
  async function addNode() { if (!title.trim()) return; setSaving(true); setAddError(""); const x = 38 + Math.random() * 25; const y = 37 + Math.random() * 28; try { const response = pickedFile ? await fetch("/api/upload", { method: "POST", body: (() => { const form = new FormData(); form.set("file", pickedFile); form.set("title", title.trim()); form.set("x", String(x)); form.set("y", String(y)); return form; })() }) : await fetch("/api/items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), type: addType, x, y, color: addType === "link" ? "green" : "blue", tags: [addType === "link" ? "Link" : "File", "New"] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not save this item."); const item = body.item; setNodes((current) => [...current, { id: item.id, title: item.title, kind: item.type === "file" ? "file" : "link", x: item.x, y: item.y, color: item.color, size: "medium", detail: pickedFile ? "Stored privately on your server." : "A new connected resource saved in your second brain.", tags: item.tags }]); setTitle(""); setPickedFile(null); setAddOpen(false); } catch (error) { setAddError(error instanceof Error ? error.message : "Could not save this item."); } finally { setSaving(false); } }
  return <main className="brain-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">N</span><div><strong>NRC</strong><small>Second Brain</small></div></div><button className="workspace-switch"><span>MK&apos;s universe</span><ChevronDown size={15} /></button><nav className="nav-list"><button className="nav-item active"><Grid2X2 size={17} /> Graph</button><button className="nav-item"><Folder size={17} /> Files</button><button className="nav-item"><FileText size={17} /> Notes</button><button className="nav-item"><Bell size={17} /> This week <span className="count">3</span></button></nav><p className="section-label">WORKSPACES</p><nav className="nav-list compact"><button className="nav-item"><span className="dot cyan" />School</button><button className="nav-item"><span className="dot blue" />Dual Enrollment</button><button className="nav-item"><span className="dot violet" />Personal</button><button className="nav-item"><span className="dot green" />Projects</button></nav><div className="sidebar-bottom"><button className="nav-item"><Settings size={17} /> Settings</button><p>Created by MK</p></div></aside>
    <section className="graph-area"><header className="topbar"><div><p className="eyebrow">YOUR SECOND BRAIN</p><h1>Everything, connected.</h1></div><div className="top-actions"><label className="search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search your universe" /></label><button className="icon-button" aria-label="Notifications"><Bell size={18} /></button><button className="avatar">MK</button></div></header><div className="graph-toolbar"><span>{nodes.length} connected items</span><div><button className="tool-button" onClick={() => { setAddType("file"); setAddOpen(true); }}><Upload size={16} /> Add file</button><button className="primary-button" onClick={() => { setAddType("link"); setAddOpen(true); }}><Plus size={17} /> Add</button></div></div><div className="constellation" aria-label="Interactive visual graph of your files and workspaces"><div className="atmosphere" /><svg className="connections" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{links.map(([from, to]) => { const a = nodes.find((node) => node.id === from); const b = nodes.find((node) => node.id === to); return a && b ? <line key={`${from}-${to}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} /> : null; })}</svg><AnimatePresence>{visibleNodes.map((node) => { const Icon = iconFor(node.kind); const isSelected = node.id === selectedId; return <motion.button key={node.id} className={`brain-node ${node.color} ${node.size} ${isSelected ? "selected" : ""}`} style={{ left: `${node.x}%`, top: `${node.y}%` }} initial={{ opacity: 0, scale: .65 }} animate={{ opacity: 1, scale: 1 }} whileHover={{ scale: 1.08 }} onClick={() => setSelectedId(node.id)}><span className="node-core"><Icon size={node.size === "large" ? 24 : 18} /></span><span className="node-label">{node.title}</span></motion.button>; })}</AnimatePresence><div className="graph-hint"><Sparkles size={15} /> Click any item to explore</div></div></section>
    <aside className="inspector"><div className="inspector-head"><span>ITEM DETAILS</span><button className="icon-button" aria-label="Close details"><X size={17} /></button></div><div className={`detail-icon ${selected.color}`}>{(() => { const Icon = iconFor(selected.kind); return <Icon size={24} />; })()}</div><h2>{selected.title}</h2><p className="type-line">{selected.kind.toUpperCase()} <span>•</span> PRIVATE</p><div className="divider" /><p className="detail-copy">{selected.detail}</p><div className="tag-row">{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="divider" /><dl><div><dt>Connected to</dt><dd>{links.filter(([a, b]) => a === selected.id || b === selected.id).length} items</dd></div><div><dt>Last updated</dt><dd>Just now</dd></div><div><dt>Storage</dt><dd>Saved on your server</dd></div></dl><div className="inspector-actions"><button className="open-button">Open item</button><button className="icon-button" aria-label="More actions"><MoreHorizontal size={18} /></button></div><div className="future-note"><Code2 size={16} /><span>GitHub connections can be enabled later in Settings.</span></div></aside>
    <AnimatePresence>{addOpen && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.form className="add-modal" onSubmit={(event) => { event.preventDefault(); void addNode(); }} initial={{ y: 14, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 14, opacity: 0 }}><div className="modal-head"><div><p className="eyebrow">NEW ITEM</p><h2>{addType === "file" ? "Add a file" : "Add a link"}</h2></div><button type="button" className="icon-button" onClick={() => setAddOpen(false)} aria-label="Close"><X size={18} /></button></div><div className="choice-row"><button type="button" className={addType === "file" ? "chosen" : ""} onClick={() => { setAddType("file"); setPickedFile(null); }}><Upload size={17} />File</button><button type="button" className={addType === "link" ? "chosen" : ""} onClick={() => { setAddType("link"); setPickedFile(null); }}><Link2 size={17} />Link</button></div>{addType === "file" && <label className="file-picker">Choose file<input type="file" accept=".pdf,.txt,.md,.docx,.pptx,.jpg,.jpeg,.png,.webp" onChange={(event) => { const file = event.target.files?.[0] ?? null; setPickedFile(file); if (file && !title) setTitle(file.name); }} /><span>{pickedFile ? pickedFile.name : "PDF, notes, docs, slides, or images"}</span></label>}<label className="field">Name<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder={addType === "file" ? "e.g. Biology notes" : "e.g. Class portal"} /></label>{addError && <p className="form-error">{addError}</p>}<button className="primary-button wide" type="submit" disabled={saving}><Plus size={17} />{saving ? "Saving..." : "Add to universe"}</button></motion.form></motion.div>}</AnimatePresence>
  </main>;
}
