"use client";

import { BrainCircuit } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Card = { id: string; front: string; back: string; dueAt: string; interval: number; workspaceId: string | null };
type Workspace = { id: string; name: string };

export default function StudyPage() {
  const router = useRouter(); const [cards, setCards] = useState<Card[]>([]); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspaceId, setWorkspaceId] = useState(""); const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [front, setFront] = useState(""); const [back, setBack] = useState(""); const [message, setMessage] = useState("");
  async function loadCards(space = workspaceId) { const response = await fetch(`/api/study${space ? `?workspaceId=${encodeURIComponent(space)}` : ""}`); if (!response.ok) return; const data = await response.json(); setCards(data.cards); setIndex(0); setFlipped(false); }
  useEffect(() => { fetch("/api/session").then((response) => response.json()).then(async (data) => { if (!data.user) { router.replace(data.setupComplete ? "/login" : "/setup"); return; } const [spaces, cardsResponse] = await Promise.all([fetch("/api/workspaces").then((response) => response.json()), fetch("/api/study").then((response) => response.json())]); setWorkspaces(spaces.workspaces || []); setCards(cardsResponse.cards || []); }); }, [router]);
  async function add(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/study", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ front, back, workspaceId: workspaceId || undefined }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error); return; } setFront(""); setBack(""); setMessage("Flashcard added."); await loadCards(); }
  async function review(rating: "again" | "good" | "easy") { const card = cards[index]; if (!card) return; await fetch(`/api/study/${card.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating }) }); await loadCards(); }
  const card = cards[index];
  return <main className="study-page"><header className="calendar-head"><a href="/">NRC Second Brain</a><span>Study space</span><a className="tool-button" href="/calendar">Calendar</a></header><section className="study-content"><div><p className="eyebrow">FLASHCARDS</p><h1>Keep what you learn.</h1><p className="settings-intro">Create cards from class notes, then review them with simple spaced repetition.</p><form className="study-form" onSubmit={add}><label>Workspace<select value={workspaceId} onChange={(event) => { setWorkspaceId(event.target.value); void loadCards(event.target.value); }}><option value="">All workspaces</option>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></label><label>Question<input value={front} onChange={(event) => setFront(event.target.value)} required placeholder="What do you need to remember?" /></label><label>Answer<textarea value={back} onChange={(event) => setBack(event.target.value)} required placeholder="Explain it in your own words" /></label><button className="primary-button">Add flashcard</button>{message && <p className="connection-message">{message}</p>}</form></div><div className="review-column">{card ? <><button className={`flashcard ${flipped ? "flipped" : ""}`} onClick={() => setFlipped(!flipped)}><span className="card-side"><small>{flipped ? "ANSWER" : "QUESTION"}</small><strong>{flipped ? card.back : card.front}</strong><em>Click to {flipped ? "see question" : "reveal answer"}</em></span></button>{flipped && <div className="review-actions"><button onClick={() => void review("again")}>Again</button><button onClick={() => void review("good")}>Good</button><button onClick={() => void review("easy")}>Easy</button></div>}</> : <div className="study-empty"><BrainCircuit size={27} /><strong>No flashcards here yet.</strong><span>Add your first one from a note or class reading.</span></div>}</div></section></main>;
}
